name: los_pasar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  intl: 0.17.0
  datetime_picker_formfield: 2.0.0
  flutter: 
    sdk: flutter
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  fonts: 
    - family: Nunito
      fonts: 
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 700
  uses-material-design: true

