name: los_pasar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  intl: 0.17.0
  datetime_picker_formfield: 2.0.0
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.17
  uuid: ^3.0.6
  flutter_easyloading: 3.0.3
  dropdown_button2: 1.4.0
  pdf: 3.7.4
  path_provider: 2.0.9
  open_file: 3.2.1
  flutter:
    sdk: flutter
  excel: ^2.0.0-null-safety-3
  bluetooth_print: ^3.0.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true
