// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2m0PzICjXU2PsmU2bRgZq8fzCBe7Nso',
    appId: '1:148021691024:android:0c9571775993df17e0ce15',
    messagingSenderId: '148021691024',
    projectId: 'los-pasar',
    storageBucket: 'los-pasar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpSkXu9X8snhEys4E7tLXvPkNwzpfBWI',
    appId: '1:148021691024:ios:a9455bd0e0c91d96e0ce15',
    messagingSenderId: '148021691024',
    projectId: 'los-pasar',
    storageBucket: 'los-pasar.appspot.com',
    androidClientId: '148021691024-45dmgie2cd6o6vffhr3l87b967ha1nce.apps.googleusercontent.com',
    iosClientId: '148021691024-6lakrnp0kjvospi90b18su4vlql3o72k.apps.googleusercontent.com',
    iosBundleId: 'com.atn.los-pasar',
  );
}
